version: "3.8"
services:
  blaze:
    image: samply/blaze:develop
    ports:
      - "8080:8080"

  test-data-loader:
    image: samply/test-data-loader
    environment:
      FHIR_STORE_URL: "http://blaze:8080/fhir"
      PATIENT_COUNT: "2000"
    command: sh -c "sleep 60 && /app/run.sh"
